language: php

php:
  - 7.1
  - 7.2

install:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --no-suggest

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
- composer test -- --coverage-clover=coverage.xml

#after_script:

after_success:
- bash <(curl -s https://codecov.io/bash)

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache